artifacts:
  artifacts_dir: artifacts
  pickle_format_data_dir: pickle_format_data
  img_pkl_file_name: img_pkl_file.pkl 
  feature_extraction_dir: extracted_features
  extracted_features_name: feature_vectors.pkl 
  upload_img_dir: upload